export type DeviceSpec = [string, string]

export type CatalogDevice = {
  name: string
  brand: string
  category: 'Smartphone' | 'Tablet' | 'Laptop' | 'Earbuds' | 'Smartwatch'
  year: string
  score: number
  mrpIN: number
  priceIN: number
  mrpUS: number
  priceUS: number
  amazonIN: string
  amazonUS: string
  specs: DeviceSpec[]
}

export const catalogDevices: CatalogDevice[] = [
  {
    name: 'Samsung Galaxy S26 Ultra',
    brand: 'Samsung',
    category: 'Smartphone',
    year: '2026',
    score: 92,
    mrpIN: 139999,
    priceIN: 138999,
    mrpUS: 1299,
    priceUS: 1279,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+S26+Ultra',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+S26+Ultra',
    specs: [['Display', '6.9in LTPO AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite Gen 5'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '5000mAh 60W']],
  },
  {
    name: 'Samsung Galaxy S25 Ultra',
    brand: 'Samsung',
    category: 'Smartphone',
    year: '2025',
    score: 90,
    mrpIN: 129999,
    priceIN: 126999,
    mrpUS: 1199,
    priceUS: 1179,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+S25+Ultra',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+S25+Ultra',
    specs: [['Display', '6.9in LTPO AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '5000mAh 45W']],
  },
  {
    name: 'Samsung Galaxy S25+',
    brand: 'Samsung',
    category: 'Smartphone',
    year: '2025',
    score: 86,
    mrpIN: 99999,
    priceIN: 96999,
    mrpUS: 999,
    priceUS: 949,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+S25%2B',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+S25%2B',
    specs: [['Display', '6.7in LTPO AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB'], ['Storage', '256GB / 512GB'], ['Battery', '4900mAh 45W']],
  },
  {
    name: 'Samsung Galaxy S25',
    brand: 'Samsung',
    category: 'Smartphone',
    year: '2025',
    score: 84,
    mrpIN: 79999,
    priceIN: 77999,
    mrpUS: 799,
    priceUS: 779,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+S25',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+S25',
    specs: [['Display', '6.2in LTPO AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB'], ['Storage', '128GB / 256GB'], ['Battery', '4000mAh 25W']],
  },
  {
    name: 'Samsung Galaxy A56',
    brand: 'Samsung',
    category: 'Smartphone',
    year: '2025',
    score: 74,
    mrpIN: 34999,
    priceIN: 33999,
    mrpUS: 399,
    priceUS: 389,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+A56',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+A56',
    specs: [['Display', '6.7in AMOLED 120Hz'], ['Processor', 'Exynos 1580'], ['RAM', '8GB / 12GB'], ['Storage', '128GB / 256GB'], ['Battery', '5000mAh 45W']],
  },
  {
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    category: 'Smartphone',
    year: '2024',
    score: 95,
    mrpIN: 159900,
    priceIN: 157000,
    mrpUS: 1199,
    priceUS: 1189,
    amazonIN: 'https://www.amazon.in/s?k=iPhone+16+Pro+Max',
    amazonUS: 'https://www.amazon.com/s?k=iPhone+16+Pro+Max',
    specs: [['Display', '6.9in Super Retina XDR 120Hz'], ['Processor', 'Apple A18 Pro'], ['RAM', '8GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '4685mAh 27W']],
  },
  {
    name: 'iPhone 16 Pro',
    brand: 'Apple',
    category: 'Smartphone',
    year: '2024',
    score: 91,
    mrpIN: 119900,
    priceIN: 117000,
    mrpUS: 999,
    priceUS: 979,
    amazonIN: 'https://www.amazon.in/s?k=iPhone+16+Pro',
    amazonUS: 'https://www.amazon.com/s?k=iPhone+16+Pro',
    specs: [['Display', '6.3in Super Retina XDR 120Hz'], ['Processor', 'Apple A18 Pro'], ['RAM', '8GB'], ['Storage', '128GB / 256GB / 512GB / 1TB'], ['Battery', '3582mAh 27W']],
  },
  {
    name: 'iPhone 16 Plus',
    brand: 'Apple',
    category: 'Smartphone',
    year: '2024',
    score: 85,
    mrpIN: 89900,
    priceIN: 87000,
    mrpUS: 899,
    priceUS: 879,
    amazonIN: 'https://www.amazon.in/s?k=iPhone+16+Plus',
    amazonUS: 'https://www.amazon.com/s?k=iPhone+16+Plus',
    specs: [['Display', '6.7in Super Retina XDR'], ['Processor', 'Apple A18'], ['RAM', '8GB'], ['Storage', '128GB / 256GB / 512GB'], ['Battery', '4674mAh 25W']],
  },
  {
    name: 'iPhone 16',
    brand: 'Apple',
    category: 'Smartphone',
    year: '2024',
    score: 83,
    mrpIN: 79900,
    priceIN: 77900,
    mrpUS: 799,
    priceUS: 779,
    amazonIN: 'https://www.amazon.in/s?k=iPhone+16',
    amazonUS: 'https://www.amazon.com/s?k=iPhone+16',
    specs: [['Display', '6.1in Super Retina XDR'], ['Processor', 'Apple A18'], ['RAM', '8GB'], ['Storage', '128GB / 256GB / 512GB'], ['Battery', '3561mAh 25W']],
  },
  {
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Smartphone',
    year: '2023',
    score: 89,
    mrpIN: 119900,
    priceIN: 109000,
    mrpUS: 1099,
    priceUS: 999,
    amazonIN: 'https://www.amazon.in/s?k=iPhone+15+Pro+Max',
    amazonUS: 'https://www.amazon.com/s?k=iPhone+15+Pro+Max',
    specs: [['Display', '6.7in Super Retina XDR 120Hz'], ['Processor', 'Apple A17 Pro'], ['RAM', '8GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '4422mAh 27W']],
  },
  {
    name: 'Google Pixel 9 Pro XL',
    brand: 'Google',
    category: 'Smartphone',
    year: '2024',
    score: 89,
    mrpIN: 129999,
    priceIN: 126999,
    mrpUS: 1099,
    priceUS: 1069,
    amazonIN: 'https://www.amazon.in/s?k=Google+Pixel+9+Pro+XL',
    amazonUS: 'https://www.amazon.com/s?k=Google+Pixel+9+Pro+XL',
    specs: [['Display', '6.8in LTPO OLED 120Hz'], ['Processor', 'Tensor G4'], ['RAM', '16GB'], ['Storage', '128GB / 256GB / 1TB'], ['Battery', '5060mAh 37W']],
  },
  {
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    category: 'Smartphone',
    year: '2024',
    score: 88,
    mrpIN: 109999,
    priceIN: 107999,
    mrpUS: 999,
    priceUS: 979,
    amazonIN: 'https://www.amazon.in/s?k=Google+Pixel+9+Pro',
    amazonUS: 'https://www.amazon.com/s?k=Google+Pixel+9+Pro',
    specs: [['Display', '6.3in LTPO OLED 120Hz'], ['Processor', 'Tensor G4'], ['RAM', '16GB'], ['Storage', '128GB / 256GB / 1TB'], ['Battery', '4700mAh 37W']],
  },
  {
    name: 'Google Pixel 9',
    brand: 'Google',
    category: 'Smartphone',
    year: '2024',
    score: 83,
    mrpIN: 79999,
    priceIN: 77999,
    mrpUS: 799,
    priceUS: 779,
    amazonIN: 'https://www.amazon.in/s?k=Google+Pixel+9',
    amazonUS: 'https://www.amazon.com/s?k=Google+Pixel+9',
    specs: [['Display', '6.3in OLED 120Hz'], ['Processor', 'Tensor G4'], ['RAM', '12GB'], ['Storage', '128GB / 256GB'], ['Battery', '4700mAh 27W']],
  },
  {
    name: 'Google Pixel 9a',
    brand: 'Google',
    category: 'Smartphone',
    year: '2025',
    score: 79,
    mrpIN: 49999,
    priceIN: 48999,
    mrpUS: 499,
    priceUS: 479,
    amazonIN: 'https://www.amazon.in/s?k=Google+Pixel+9a',
    amazonUS: 'https://www.amazon.com/s?k=Google+Pixel+9a',
    specs: [['Display', '6.3in OLED 120Hz'], ['Processor', 'Tensor G4'], ['RAM', '8GB'], ['Storage', '128GB / 256GB'], ['Battery', '5100mAh 23W']],
  },
  {
    name: 'OnePlus 13',
    brand: 'OnePlus',
    category: 'Smartphone',
    year: '2025',
    score: 85,
    mrpIN: 69999,
    priceIN: 67999,
    mrpUS: 799,
    priceUS: 789,
    amazonIN: 'https://www.amazon.in/s?k=OnePlus+13',
    amazonUS: 'https://www.amazon.com/s?k=OnePlus+13',
    specs: [['Display', '6.82in LTPO AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB / 16GB / 24GB'], ['Storage', '256GB / 512GB'], ['Battery', '6000mAh 100W']],
  },
  {
    name: 'OnePlus 13R',
    brand: 'OnePlus',
    category: 'Smartphone',
    year: '2025',
    score: 78,
    mrpIN: 42999,
    priceIN: 41999,
    mrpUS: 499,
    priceUS: 489,
    amazonIN: 'https://www.amazon.in/s?k=OnePlus+13R',
    amazonUS: 'https://www.amazon.com/s?k=OnePlus+13R',
    specs: [['Display', '6.78in AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Gen 3'], ['RAM', '8GB / 16GB'], ['Storage', '128GB / 256GB'], ['Battery', '6000mAh 80W']],
  },
  {
    name: 'OnePlus Nord 4',
    brand: 'OnePlus',
    category: 'Smartphone',
    year: '2024',
    score: 72,
    mrpIN: 29999,
    priceIN: 28999,
    mrpUS: 349,
    priceUS: 339,
    amazonIN: 'https://www.amazon.in/s?k=OnePlus+Nord+4',
    amazonUS: 'https://www.amazon.com/s?k=OnePlus+Nord+4',
    specs: [['Display', '6.74in AMOLED 120Hz'], ['Processor', 'Snapdragon 7+ Gen 3'], ['RAM', '8GB / 12GB'], ['Storage', '256GB / 512GB'], ['Battery', '5500mAh 100W']],
  },
  {
    name: 'Xiaomi 15',
    brand: 'Xiaomi',
    category: 'Smartphone',
    year: '2025',
    score: 87,
    mrpIN: 89999,
    priceIN: 87999,
    mrpUS: 799,
    priceUS: 779,
    amazonIN: 'https://www.amazon.in/s?k=Xiaomi+15',
    amazonUS: 'https://www.amazon.com/s?k=Xiaomi+15',
    specs: [['Display', '6.36in OLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB'], ['Battery', '5240mAh 90W']],
  },
  {
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    category: 'Smartphone',
    year: '2024',
    score: 86,
    mrpIN: 99999,
    priceIN: 97999,
    mrpUS: 899,
    priceUS: 879,
    amazonIN: 'https://www.amazon.in/s?k=Xiaomi+14+Ultra',
    amazonUS: 'https://www.amazon.com/s?k=Xiaomi+14+Ultra',
    specs: [['Display', '6.73in LTPO AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Gen 3'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '5000mAh 90W']],
  },
  {
    name: 'Nothing Phone 3',
    brand: 'Nothing',
    category: 'Smartphone',
    year: '2025',
    score: 80,
    mrpIN: 59999,
    priceIN: 57999,
    mrpUS: 649,
    priceUS: 629,
    amazonIN: 'https://www.amazon.in/s?k=Nothing+Phone+3',
    amazonUS: 'https://www.amazon.com/s?k=Nothing+Phone+3',
    specs: [['Display', '6.67in AMOLED 120Hz'], ['Processor', 'Snapdragon 8s Gen 3'], ['RAM', '8GB / 12GB'], ['Storage', '128GB / 256GB'], ['Battery', '4700mAh 65W']],
  },
  {
    name: 'Nothing Phone 2a Plus',
    brand: 'Nothing',
    category: 'Smartphone',
    year: '2024',
    score: 70,
    mrpIN: 24999,
    priceIN: 23999,
    mrpUS: 299,
    priceUS: 289,
    amazonIN: 'https://www.amazon.in/s?k=Nothing+Phone+2a+Plus',
    amazonUS: 'https://www.amazon.com/s?k=Nothing+Phone+2a+Plus',
    specs: [['Display', '6.7in AMOLED 120Hz'], ['Processor', 'Dimensity 7350 Pro'], ['RAM', '8GB / 12GB'], ['Storage', '128GB / 256GB'], ['Battery', '5000mAh 45W']],
  },
  {
    name: 'Sony Xperia 1 VI',
    brand: 'Sony',
    category: 'Smartphone',
    year: '2024',
    score: 82,
    mrpIN: 129990,
    priceIN: 124999,
    mrpUS: 1299,
    priceUS: 1249,
    amazonIN: 'https://www.amazon.in/s?k=Sony+Xperia+1+VI',
    amazonUS: 'https://www.amazon.com/s?k=Sony+Xperia+1+VI',
    specs: [['Display', '6.5in OLED 120Hz'], ['Processor', 'Snapdragon 8 Gen 3'], ['RAM', '12GB'], ['Storage', '256GB / 512GB'], ['Battery', '5000mAh 30W']],
  },
  {
    name: 'Motorola Edge 50 Ultra',
    brand: 'Motorola',
    category: 'Smartphone',
    year: '2025',
    score: 79,
    mrpIN: 59999,
    priceIN: 56999,
    mrpUS: 699,
    priceUS: 649,
    amazonIN: 'https://www.amazon.in/s?k=Motorola+Edge+50+Ultra',
    amazonUS: 'https://www.amazon.com/s?k=Motorola+Edge+50+Ultra',
    specs: [['Display', '6.7in pOLED 144Hz'], ['Processor', 'Snapdragon 8s Gen 3'], ['RAM', '12GB / 16GB'], ['Storage', '512GB / 1TB'], ['Battery', '4500mAh 125W']],
  },
  {
    name: 'ASUS ROG Phone 9',
    brand: 'ASUS',
    category: 'Smartphone',
    year: '2025',
    score: 88,
    mrpIN: 99999,
    priceIN: 94999,
    mrpUS: 1199,
    priceUS: 1099,
    amazonIN: 'https://www.amazon.in/s?k=ASUS+ROG+Phone+9',
    amazonUS: 'https://www.amazon.com/s?k=ASUS+ROG+Phone+9',
    specs: [['Display', '6.78in AMOLED 165Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '16GB / 24GB'], ['Storage', '512GB / 1TB'], ['Battery', '5800mAh 65W']],
  },
  {
    name: 'iPad Pro M4 13-inch',
    brand: 'Apple',
    category: 'Tablet',
    year: '2024',
    score: 96,
    mrpIN: 169900,
    priceIN: 165000,
    mrpUS: 1299,
    priceUS: 1279,
    amazonIN: 'https://www.amazon.in/s?k=iPad+Pro+M4+13',
    amazonUS: 'https://www.amazon.com/s?k=iPad+Pro+M4+13',
    specs: [['Display', '13in OLED 120Hz'], ['Processor', 'Apple M4'], ['RAM', '16GB'], ['Storage', '256GB / 512GB / 1TB / 2TB'], ['Battery', '40.88Wh']],
  },
  {
    name: 'iPad Pro M4 11-inch',
    brand: 'Apple',
    category: 'Tablet',
    year: '2024',
    score: 94,
    mrpIN: 99900,
    priceIN: 97000,
    mrpUS: 999,
    priceUS: 979,
    amazonIN: 'https://www.amazon.in/s?k=iPad+Pro+M4+11',
    amazonUS: 'https://www.amazon.com/s?k=iPad+Pro+M4+11',
    specs: [['Display', '11in OLED 120Hz'], ['Processor', 'Apple M4'], ['RAM', '8GB / 16GB'], ['Storage', '256GB / 512GB / 1TB / 2TB'], ['Battery', '31.29Wh']],
  },
  {
    name: 'iPad Air M2 13-inch',
    brand: 'Apple',
    category: 'Tablet',
    year: '2024',
    score: 88,
    mrpIN: 99900,
    priceIN: 96999,
    mrpUS: 799,
    priceUS: 779,
    amazonIN: 'https://www.amazon.in/s?k=iPad+Air+M2+13',
    amazonUS: 'https://www.amazon.com/s?k=iPad+Air+M2+13',
    specs: [['Display', '13in Liquid Retina'], ['Processor', 'Apple M2'], ['RAM', '8GB'], ['Storage', '128GB / 256GB / 512GB / 1TB'], ['Battery', '36.59Wh']],
  },
  {
    name: 'iPad Air M2 11-inch',
    brand: 'Apple',
    category: 'Tablet',
    year: '2024',
    score: 86,
    mrpIN: 69900,
    priceIN: 67999,
    mrpUS: 599,
    priceUS: 579,
    amazonIN: 'https://www.amazon.in/s?k=iPad+Air+M2+11',
    amazonUS: 'https://www.amazon.com/s?k=iPad+Air+M2+11',
    specs: [['Display', '11in Liquid Retina'], ['Processor', 'Apple M2'], ['RAM', '8GB'], ['Storage', '128GB / 256GB / 512GB / 1TB'], ['Battery', '28.93Wh']],
  },
  {
    name: 'iPad 10th Gen',
    brand: 'Apple',
    category: 'Tablet',
    year: '2022',
    score: 78,
    mrpIN: 44900,
    priceIN: 42999,
    mrpUS: 349,
    priceUS: 339,
    amazonIN: 'https://www.amazon.in/s?k=iPad+10th+generation',
    amazonUS: 'https://www.amazon.com/s?k=iPad+10th+generation',
    specs: [['Display', '10.9in Liquid Retina'], ['Processor', 'Apple A14 Bionic'], ['RAM', '4GB'], ['Storage', '64GB / 256GB'], ['Battery', '28.65Wh']],
  },
  {
    name: 'Samsung Galaxy Tab S10 Ultra',
    brand: 'Samsung',
    category: 'Tablet',
    year: '2024',
    score: 87,
    mrpIN: 118999,
    priceIN: 115999,
    mrpUS: 1099,
    priceUS: 1069,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+S10+Ultra',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Tab+S10+Ultra',
    specs: [['Display', '14.6in AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Gen 3'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '11200mAh']],
  },
  {
    name: 'Samsung Galaxy Tab S10+',
    brand: 'Samsung',
    category: 'Tablet',
    year: '2024',
    score: 85,
    mrpIN: 89999,
    priceIN: 86999,
    mrpUS: 899,
    priceUS: 879,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+S10%2B',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Tab+S10%2B',
    specs: [['Display', '12.4in AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Gen 3'], ['RAM', '12GB'], ['Storage', '256GB / 512GB'], ['Battery', '10090mAh']],
  },
  {
    name: 'Samsung Galaxy Tab S10 FE',
    brand: 'Samsung',
    category: 'Tablet',
    year: '2025',
    score: 76,
    mrpIN: 49999,
    priceIN: 47999,
    mrpUS: 449,
    priceUS: 429,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+S10+FE',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Tab+S10+FE',
    specs: [['Display', '10.9in LTPS TFT 90Hz'], ['Processor', 'Exynos 1580'], ['RAM', '6GB / 8GB'], ['Storage', '128GB / 256GB'], ['Battery', '8000mAh 45W']],
  },
  {
    name: 'OnePlus Pad 2',
    brand: 'OnePlus',
    category: 'Tablet',
    year: '2025',
    score: 82,
    mrpIN: 42999,
    priceIN: 39999,
    mrpUS: 549,
    priceUS: 519,
    amazonIN: 'https://www.amazon.in/s?k=OnePlus+Pad+2',
    amazonUS: 'https://www.amazon.com/s?k=OnePlus+Pad+2',
    specs: [['Display', '12.1in LCD 144Hz'], ['Processor', 'Snapdragon 8 Gen 3'], ['RAM', '8GB / 12GB'], ['Storage', '128GB / 256GB'], ['Battery', '9510mAh 67W']],
  },
  {
    name: 'Xiaomi Pad 7 Pro',
    brand: 'Xiaomi',
    category: 'Tablet',
    year: '2025',
    score: 80,
    mrpIN: 44999,
    priceIN: 41999,
    mrpUS: 549,
    priceUS: 529,
    amazonIN: 'https://www.amazon.in/s?k=Xiaomi+Pad+7+Pro',
    amazonUS: 'https://www.amazon.com/s?k=Xiaomi+Pad+7+Pro',
    specs: [['Display', '11.2in 3.2K LCD 144Hz'], ['Processor', 'Snapdragon 8s Gen 3'], ['RAM', '8GB / 12GB'], ['Storage', '128GB / 256GB / 512GB'], ['Battery', '8850mAh 67W']],
  },
  {
    name: 'MacBook Air M4 15-inch',
    brand: 'Apple',
    category: 'Laptop',
    year: '2025',
    score: 94,
    mrpIN: 134900,
    priceIN: 130000,
    mrpUS: 1299,
    priceUS: 1279,
    amazonIN: 'https://www.amazon.in/s?k=MacBook+Air+M4+15',
    amazonUS: 'https://www.amazon.com/s?k=MacBook+Air+M4+15',
    specs: [['Display', '15.3in Liquid Retina'], ['Processor', 'Apple M4'], ['RAM', '16GB / 32GB'], ['Storage', '256GB / 512GB / 1TB / 2TB'], ['Battery', '66.5Wh']],
  },
  {
    name: 'MacBook Air M4 13-inch',
    brand: 'Apple',
    category: 'Laptop',
    year: '2025',
    score: 93,
    mrpIN: 114900,
    priceIN: 112000,
    mrpUS: 1099,
    priceUS: 1079,
    amazonIN: 'https://www.amazon.in/s?k=MacBook+Air+M4+13',
    amazonUS: 'https://www.amazon.com/s?k=MacBook+Air+M4+13',
    specs: [['Display', '13.6in Liquid Retina'], ['Processor', 'Apple M4'], ['RAM', '16GB / 32GB'], ['Storage', '256GB / 512GB / 1TB / 2TB'], ['Battery', '52.6Wh']],
  },
  {
    name: 'MacBook Pro M4 14-inch',
    brand: 'Apple',
    category: 'Laptop',
    year: '2024',
    score: 96,
    mrpIN: 169900,
    priceIN: 165000,
    mrpUS: 1599,
    priceUS: 1559,
    amazonIN: 'https://www.amazon.in/s?k=MacBook+Pro+M4+14',
    amazonUS: 'https://www.amazon.com/s?k=MacBook+Pro+M4+14',
    specs: [['Display', '14.2in Liquid Retina XDR 120Hz'], ['Processor', 'Apple M4 Pro'], ['RAM', '24GB / 48GB'], ['Storage', '512GB / 1TB / 2TB'], ['Battery', '72.4Wh']],
  },
  {
    name: 'MacBook Pro M4 16-inch',
    brand: 'Apple',
    category: 'Laptop',
    year: '2024',
    score: 97,
    mrpIN: 249900,
    priceIN: 239000,
    mrpUS: 2499,
    priceUS: 2449,
    amazonIN: 'https://www.amazon.in/s?k=MacBook+Pro+M4+16',
    amazonUS: 'https://www.amazon.com/s?k=MacBook+Pro+M4+16',
    specs: [['Display', '16.2in Liquid Retina XDR 120Hz'], ['Processor', 'Apple M4 Max'], ['RAM', '48GB / 128GB'], ['Storage', '1TB / 2TB / 4TB'], ['Battery', '99.6Wh']],
  },
  {
    name: 'Dell XPS 14 (2025)',
    brand: 'Dell',
    category: 'Laptop',
    year: '2025',
    score: 89,
    mrpIN: 189999,
    priceIN: 179999,
    mrpUS: 2099,
    priceUS: 1999,
    amazonIN: 'https://www.amazon.in/s?k=Dell+XPS+14+2025',
    amazonUS: 'https://www.amazon.com/s?k=Dell+XPS+14+2025',
    specs: [['Display', '14.5in OLED 120Hz'], ['Processor', 'Intel Core Ultra 9'], ['RAM', '32GB'], ['Storage', '1TB SSD'], ['Battery', '69.5Wh']],
  },
  {
    name: 'Lenovo Legion Pro 7i Gen 10',
    brand: 'Lenovo',
    category: 'Laptop',
    year: '2025',
    score: 90,
    mrpIN: 269999,
    priceIN: 249999,
    mrpUS: 2999,
    priceUS: 2799,
    amazonIN: 'https://www.amazon.in/s?k=Lenovo+Legion+Pro+7i+Gen+10',
    amazonUS: 'https://www.amazon.com/s?k=Lenovo+Legion+Pro+7i+Gen+10',
    specs: [['Display', '16in QHD+ 240Hz'], ['Processor', 'Intel Core Ultra 9'], ['RAM', '32GB / 64GB'], ['Storage', '1TB / 2TB SSD'], ['Battery', '99.9Wh']],
  },
  {
    name: 'AirPods Pro 2nd Gen',
    brand: 'Apple',
    category: 'Earbuds',
    year: '2022',
    score: 91,
    mrpIN: 24900,
    priceIN: 22999,
    mrpUS: 249,
    priceUS: 229,
    amazonIN: 'https://www.amazon.in/s?k=AirPods+Pro+2nd+Gen',
    amazonUS: 'https://www.amazon.com/s?k=AirPods+Pro+2nd+Gen',
    specs: [['Type', 'In-ear TWS ANC'], ['Chip', 'Apple H2'], ['Battery', '6hr + 24hr case'], ['Connectivity', 'Bluetooth 5.3'], ['Water', 'IPX4']],
  },
  {
    name: 'Sony WF-1000XM5',
    brand: 'Sony',
    category: 'Earbuds',
    year: '2023',
    score: 93,
    mrpIN: 19990,
    priceIN: 17999,
    mrpUS: 279,
    priceUS: 249,
    amazonIN: 'https://www.amazon.in/s?k=Sony+WF-1000XM5',
    amazonUS: 'https://www.amazon.com/s?k=Sony+WF-1000XM5',
    specs: [['Type', 'In-ear TWS ANC'], ['Driver', '8.4mm dynamic'], ['Battery', '8hr + 24hr case'], ['Connectivity', 'Bluetooth 5.3'], ['Water', 'IPX4']],
  },
  {
    name: 'Samsung Galaxy Buds3 Pro',
    brand: 'Samsung',
    category: 'Earbuds',
    year: '2024',
    score: 85,
    mrpIN: 17999,
    priceIN: 16999,
    mrpUS: 199,
    priceUS: 189,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Buds3+Pro',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Buds3+Pro',
    specs: [['Type', 'In-ear TWS ANC'], ['Driver', '10.5mm dynamic'], ['Battery', '6hr + 21hr case'], ['Connectivity', 'Bluetooth 5.4'], ['Water', 'IPX7']],
  },
  {
    name: 'Nothing Ear (3)',
    brand: 'Nothing',
    category: 'Earbuds',
    year: '2025',
    score: 80,
    mrpIN: 9999,
    priceIN: 9499,
    mrpUS: 149,
    priceUS: 139,
    amazonIN: 'https://www.amazon.in/s?k=Nothing+Ear+3',
    amazonUS: 'https://www.amazon.com/s?k=Nothing+Ear+3',
    specs: [['Type', 'In-ear TWS ANC'], ['Driver', '11mm dynamic'], ['Battery', '8hr + 40hr case'], ['Connectivity', 'Bluetooth 5.3'], ['Water', 'IP55']],
  },
  {
    name: 'Apple Watch Series 10',
    brand: 'Apple',
    category: 'Smartwatch',
    year: '2024',
    score: 90,
    mrpIN: 46900,
    priceIN: 44999,
    mrpUS: 399,
    priceUS: 379,
    amazonIN: 'https://www.amazon.in/s?k=Apple+Watch+Series+10',
    amazonUS: 'https://www.amazon.com/s?k=Apple+Watch+Series+10',
    specs: [['Display', '1.99in LTPO OLED'], ['Chip', 'S10'], ['Health', 'ECG, blood oxygen, crash detection'], ['Battery', 'Up to 36 hours'], ['OS', 'watchOS 11']],
  },
  {
    name: 'Samsung Galaxy Watch 7',
    brand: 'Samsung',
    category: 'Smartwatch',
    year: '2024',
    score: 84,
    mrpIN: 29999,
    priceIN: 27999,
    mrpUS: 299,
    priceUS: 279,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Watch+7',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Watch+7',
    specs: [['Display', '1.47in AMOLED'], ['Chip', 'Exynos W1000'], ['Health', 'ECG, SpO2, body composition'], ['Battery', 'Up to 40 hours'], ['OS', 'Wear OS 5']],
  },
  {
    name: 'Google Pixel Watch 3',
    brand: 'Google',
    category: 'Smartwatch',
    year: '2025',
    score: 86,
    mrpIN: 39999,
    priceIN: 36999,
    mrpUS: 349,
    priceUS: 329,
    amazonIN: 'https://www.amazon.in/s?k=Google+Pixel+Watch+3',
    amazonUS: 'https://www.amazon.com/s?k=Google+Pixel+Watch+3',
    specs: [['Display', '1.4in AMOLED'], ['Chip', 'Qualcomm SW5100'], ['Health', 'Fitbit suite + ECG'], ['Battery', 'Up to 48 hours'], ['OS', 'Wear OS 5']],
  },
  {
    name: 'Samsung Galaxy Z Fold 7',
    brand: 'Samsung',
    category: 'Smartphone',
    year: '2026',
    score: 90,
    mrpIN: 169999,
    priceIN: 164999,
    mrpUS: 1899,
    priceUS: 1799,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Z+Fold+7',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Z+Fold+7',
    specs: [['Display', '7.9in foldable AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '4800mAh 45W']],
  },
  {
    name: 'Samsung Galaxy Z Flip 7',
    brand: 'Samsung',
    category: 'Smartphone',
    year: '2026',
    score: 85,
    mrpIN: 109999,
    priceIN: 104999,
    mrpUS: 1099,
    priceUS: 999,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Z+Flip+7',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Z+Flip+7',
    specs: [['Display', '6.8in foldable AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB'], ['Storage', '256GB / 512GB'], ['Battery', '4200mAh 45W']],
  },
  {
    name: 'iPhone 16e',
    brand: 'Apple',
    category: 'Smartphone',
    year: '2025',
    score: 81,
    mrpIN: 59900,
    priceIN: 57900,
    mrpUS: 699,
    priceUS: 669,
    amazonIN: 'https://www.amazon.in/s?k=iPhone+16e',
    amazonUS: 'https://www.amazon.com/s?k=iPhone+16e',
    specs: [['Display', '6.1in Super Retina XDR'], ['Processor', 'Apple A18'], ['RAM', '8GB'], ['Storage', '128GB / 256GB'], ['Battery', '3500mAh']],
  },
  {
    name: 'Google Pixel 10 Pro',
    brand: 'Google',
    category: 'Smartphone',
    year: '2026',
    score: 90,
    mrpIN: 119999,
    priceIN: 114999,
    mrpUS: 1099,
    priceUS: 1049,
    amazonIN: 'https://www.amazon.in/s?k=Google+Pixel+10+Pro',
    amazonUS: 'https://www.amazon.com/s?k=Google+Pixel+10+Pro',
    specs: [['Display', '6.4in LTPO OLED 120Hz'], ['Processor', 'Tensor G5'], ['RAM', '16GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '5000mAh 45W']],
  },
  {
    name: 'OnePlus Open 2',
    brand: 'OnePlus',
    category: 'Smartphone',
    year: '2026',
    score: 86,
    mrpIN: 149999,
    priceIN: 142999,
    mrpUS: 1699,
    priceUS: 1599,
    amazonIN: 'https://www.amazon.in/s?k=OnePlus+Open+2',
    amazonUS: 'https://www.amazon.com/s?k=OnePlus+Open+2',
    specs: [['Display', '7.8in foldable AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '16GB'], ['Storage', '512GB / 1TB'], ['Battery', '5100mAh 80W']],
  },
  {
    name: 'Xiaomi 15 Ultra',
    brand: 'Xiaomi',
    category: 'Smartphone',
    year: '2026',
    score: 89,
    mrpIN: 109999,
    priceIN: 104999,
    mrpUS: 1099,
    priceUS: 999,
    amazonIN: 'https://www.amazon.in/s?k=Xiaomi+15+Ultra',
    amazonUS: 'https://www.amazon.com/s?k=Xiaomi+15+Ultra',
    specs: [['Display', '6.73in LTPO AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '16GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '5300mAh 90W']],
  },
  {
    name: 'iPad Mini 8',
    brand: 'Apple',
    category: 'Tablet',
    year: '2026',
    score: 84,
    mrpIN: 59900,
    priceIN: 56900,
    mrpUS: 599,
    priceUS: 569,
    amazonIN: 'https://www.amazon.in/s?k=iPad+Mini+8',
    amazonUS: 'https://www.amazon.com/s?k=iPad+Mini+8',
    specs: [['Display', '8.4in Liquid Retina'], ['Processor', 'Apple A18'], ['RAM', '8GB'], ['Storage', '128GB / 256GB / 512GB'], ['Battery', 'All-day battery']],
  },
  {
    name: 'Samsung Galaxy Tab S11 Ultra',
    brand: 'Samsung',
    category: 'Tablet',
    year: '2026',
    score: 88,
    mrpIN: 124999,
    priceIN: 119999,
    mrpUS: 1199,
    priceUS: 1149,
    amazonIN: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+S11+Ultra',
    amazonUS: 'https://www.amazon.com/s?k=Samsung+Galaxy+Tab+S11+Ultra',
    specs: [['Display', '14.6in AMOLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB / 1TB'], ['Battery', '11500mAh 45W']],
  },
  {
    name: 'ASUS Zenbook 14 OLED (2026)',
    brand: 'ASUS',
    category: 'Laptop',
    year: '2026',
    score: 88,
    mrpIN: 139999,
    priceIN: 129999,
    mrpUS: 1599,
    priceUS: 1499,
    amazonIN: 'https://www.amazon.in/s?k=ASUS+Zenbook+14+OLED+2026',
    amazonUS: 'https://www.amazon.com/s?k=ASUS+Zenbook+14+OLED+2026',
    specs: [['Display', '14in OLED 120Hz'], ['Processor', 'Intel Core Ultra 7'], ['RAM', '16GB / 32GB'], ['Storage', '1TB SSD'], ['Battery', '75Wh']],
  },
  {
    name: 'HP Spectre x360 14 (2026)',
    brand: 'HP',
    category: 'Laptop',
    year: '2026',
    score: 87,
    mrpIN: 164999,
    priceIN: 154999,
    mrpUS: 1799,
    priceUS: 1699,
    amazonIN: 'https://www.amazon.in/s?k=HP+Spectre+x360+14+2026',
    amazonUS: 'https://www.amazon.com/s?k=HP+Spectre+x360+14+2026',
    specs: [['Display', '13.5in OLED touch 120Hz'], ['Processor', 'Intel Core Ultra 7'], ['RAM', '16GB / 32GB'], ['Storage', '1TB / 2TB SSD'], ['Battery', '68Wh']],
  },
  {
    name: 'Bose QuietComfort Ultra Earbuds',
    brand: 'Bose',
    category: 'Earbuds',
    year: '2025',
    score: 89,
    mrpIN: 26999,
    priceIN: 24999,
    mrpUS: 299,
    priceUS: 269,
    amazonIN: 'https://www.amazon.in/s?k=Bose+QuietComfort+Ultra+Earbuds',
    amazonUS: 'https://www.amazon.com/s?k=Bose+QuietComfort+Ultra+Earbuds',
    specs: [['Type', 'In-ear TWS ANC'], ['Audio', 'Immersive spatial audio'], ['Battery', '6hr + 24hr case'], ['Connectivity', 'Bluetooth 5.3'], ['Water', 'IPX4']],
  },
  {
    name: 'Jabra Elite 10 Gen 2',
    brand: 'Jabra',
    category: 'Earbuds',
    year: '2025',
    score: 84,
    mrpIN: 19999,
    priceIN: 17999,
    mrpUS: 249,
    priceUS: 219,
    amazonIN: 'https://www.amazon.in/s?k=Jabra+Elite+10+Gen+2',
    amazonUS: 'https://www.amazon.com/s?k=Jabra+Elite+10+Gen+2',
    specs: [['Type', 'In-ear TWS ANC'], ['Driver', '10mm'], ['Battery', '8hr + 27hr case'], ['Connectivity', 'Bluetooth multipoint'], ['Water', 'IP57']],
  },
  {
    name: 'OnePlus Watch 3',
    brand: 'OnePlus',
    category: 'Smartwatch',
    year: '2026',
    score: 83,
    mrpIN: 32999,
    priceIN: 29999,
    mrpUS: 329,
    priceUS: 299,
    amazonIN: 'https://www.amazon.in/s?k=OnePlus+Watch+3',
    amazonUS: 'https://www.amazon.com/s?k=OnePlus+Watch+3',
    specs: [['Display', '1.5in AMOLED'], ['Chip', 'Snapdragon W5 Gen 2'], ['Health', 'Heart rate, SpO2, sleep'], ['Battery', 'Up to 100 hours'], ['OS', 'Wear OS']],
  },
  {
    name: 'Garmin Venu 4',
    brand: 'Garmin',
    category: 'Smartwatch',
    year: '2026',
    score: 85,
    mrpIN: 42999,
    priceIN: 39999,
    mrpUS: 449,
    priceUS: 419,
    amazonIN: 'https://www.amazon.in/s?k=Garmin+Venu+4',
    amazonUS: 'https://www.amazon.com/s?k=Garmin+Venu+4',
    specs: [['Display', '1.4in AMOLED'], ['Sensors', 'GNSS, HR, SpO2, ECG'], ['Health', 'Advanced fitness metrics'], ['Battery', 'Up to 12 days'], ['OS', 'Garmin OS']],
  },
  {
    name: 'OPPO Find X8 Pro',
    brand: 'OPPO',
    category: 'Smartphone',
    year: '2026',
    score: 86,
    mrpIN: 104999,
    priceIN: 99999,
    mrpUS: 1099,
    priceUS: 1029,
    amazonIN: 'https://www.amazon.in/s?k=OPPO+Find+X8+Pro',
    amazonUS: 'https://www.amazon.com/s?k=OPPO+Find+X8+Pro',
    specs: [['Display', '6.8in AMOLED 120Hz'], ['Processor', 'Dimensity 9400'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB'], ['Battery', '5600mAh 100W']],
  },
  {
    name: 'vivo X200 Pro',
    brand: 'vivo',
    category: 'Smartphone',
    year: '2026',
    score: 87,
    mrpIN: 99999,
    priceIN: 95999,
    mrpUS: 1099,
    priceUS: 999,
    amazonIN: 'https://www.amazon.in/s?k=vivo+X200+Pro',
    amazonUS: 'https://www.amazon.com/s?k=vivo+X200+Pro',
    specs: [['Display', '6.78in LTPO AMOLED 120Hz'], ['Processor', 'Dimensity 9400'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB'], ['Battery', '6000mAh 90W']],
  },
  {
    name: 'Honor Magic 7 Pro',
    brand: 'Honor',
    category: 'Smartphone',
    year: '2026',
    score: 85,
    mrpIN: 94999,
    priceIN: 89999,
    mrpUS: 999,
    priceUS: 939,
    amazonIN: 'https://www.amazon.in/s?k=Honor+Magic+7+Pro',
    amazonUS: 'https://www.amazon.com/s?k=Honor+Magic+7+Pro',
    specs: [['Display', '6.8in OLED 120Hz'], ['Processor', 'Snapdragon 8 Elite'], ['RAM', '12GB / 16GB'], ['Storage', '256GB / 512GB'], ['Battery', '5600mAh 100W']],
  },
  {
    name: 'Acer Swift X 16 (2026)',
    brand: 'Acer',
    category: 'Laptop',
    year: '2026',
    score: 84,
    mrpIN: 149999,
    priceIN: 139999,
    mrpUS: 1599,
    priceUS: 1499,
    amazonIN: 'https://www.amazon.in/s?k=Acer+Swift+X+16+2026',
    amazonUS: 'https://www.amazon.com/s?k=Acer+Swift+X+16+2026',
    specs: [['Display', '16in OLED 120Hz'], ['Processor', 'AMD Ryzen AI 9'], ['RAM', '16GB / 32GB'], ['Storage', '1TB SSD'], ['Battery', '76Wh']],
  },
  {
    name: 'MSI Stealth 14 AI Studio (2026)',
    brand: 'MSI',
    category: 'Laptop',
    year: '2026',
    score: 86,
    mrpIN: 219999,
    priceIN: 204999,
    mrpUS: 2399,
    priceUS: 2199,
    amazonIN: 'https://www.amazon.in/s?k=MSI+Stealth+14+AI+Studio+2026',
    amazonUS: 'https://www.amazon.com/s?k=MSI+Stealth+14+AI+Studio+2026',
    specs: [['Display', '14in OLED 120Hz'], ['Processor', 'Intel Core Ultra 9'], ['RAM', '32GB'], ['Storage', '1TB / 2TB SSD'], ['Battery', '72Wh']],
  },
]

export const formatInr = (value: number) => `INR ${value.toLocaleString('en-IN')}`
export const formatUsd = (value: number) => `USD ${value.toLocaleString('en-US')}`

export const monogramForDevice = (name: string): string =>
  name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? '')
    .join('')

export const trackerRange = (device: CatalogDevice) => {
  const low = Math.round(device.priceIN * 0.94)
  const high = Math.max(device.mrpIN, Math.round(device.priceIN * 1.03))
  return { low, high }
}
